# Generated by Django 2.0.7 on 2018-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='URL')),
                ('shortcode', models.CharField(blank=True, max_length=10, unique=True, verbose_name='ShortCode')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
            ],
            options={
                'verbose_name_plural': 'Links',
                'ordering': ('-date',),
            },
        ),
    ]
